CREATE OR REPLACE VIEW VW_WO_REVENUE AS
SELECT WORK_ORDER_NUMBER, SUM(WORK_UNIT_QTY * ITEM_RATE) AS ESTIMATED_REVENUE
FROM FACT_WORK_UNIT_REVENUE
GROUP BY WORK_ORDER_NUMBER;

CREATE OR REPLACE VIEW VW_WO_LABOR AS
SELECT
    D.WORK_ORDER_NUMBER,
    SUM(D.ON_SITE_HOURS) AS TOTAL_HOURS,
    SUM(IFF(D.TECH_SUBSIDIARY = 'Pearce Services Global', D.ON_SITE_HOURS, 0)) AS PSG_HOURS,
    SUM(IFF(D.TECH_SUBSIDIARY = 'Pearce Services', D.ON_SITE_HOURS, 0)) AS US_HOURS,
    SUM(IFF(LOWER(D.DUMMY_UNIT) LIKE '%travel%', D.ON_SITE_HOURS, 0)) AS TRAVEL_HOURS,
    SUM(IFF(REGEXP_LIKE(LOWER(D.DUMMY_UNIT), 'rework|correction'), D.ON_SITE_HOURS, 0)) AS REWORK_HOURS,
    SUM(D.ON_SITE_HOURS * COALESCE(R.HOURLY_RATE, 0)) AS LABOR_COST
FROM FACT_DWR_LABOR D
LEFT JOIN DIM_LABOR_RATE R
    ON D.TECH_SUBSIDIARY = R.TECH_SUBSIDIARY
GROUP BY D.WORK_ORDER_NUMBER;

CREATE OR REPLACE VIEW VW_WO_PNL AS
WITH BILL AS (
    SELECT WORK_ORDER_NUMBER, SUM(BILLED_AMOUNT) AS BILLED_REVENUE
    FROM FACT_BILLING GROUP BY WORK_ORDER_NUMBER
), OTHER_COST AS (
    SELECT WORK_ORDER_NUMBER, SUM(AMOUNT) AS OTHER_COST
    FROM FACT_OTHER_COST GROUP BY WORK_ORDER_NUMBER
)
SELECT
    W.*,
    COALESCE(R.ESTIMATED_REVENUE, 0) AS ESTIMATED_REVENUE,
    COALESCE(B.BILLED_REVENUE, 0) AS BILLED_REVENUE,
    COALESCE(L.TOTAL_HOURS, 0) AS TOTAL_HOURS,
    COALESCE(L.PSG_HOURS, 0) AS PSG_HOURS,
    COALESCE(L.US_HOURS, 0) AS US_HOURS,
    COALESCE(L.TRAVEL_HOURS, 0) AS TRAVEL_HOURS,
    COALESCE(L.REWORK_HOURS, 0) AS REWORK_HOURS,
    COALESCE(L.LABOR_COST, 0) AS LABOR_COST,
    COALESCE(O.OTHER_COST, 0) AS OTHER_COST,
    COALESCE(L.LABOR_COST, 0) + COALESCE(O.OTHER_COST, 0) AS ACTUAL_COST,
    GREATEST(COALESCE(R.ESTIMATED_REVENUE, 0), COALESCE(B.BILLED_REVENUE, 0)) AS FORECAST_REVENUE,
    GREATEST(COALESCE(R.ESTIMATED_REVENUE, 0), COALESCE(B.BILLED_REVENUE, 0))
      - COALESCE(L.LABOR_COST, 0) - COALESCE(O.OTHER_COST, 0) AS FORECAST_MARGIN
FROM DIM_WORK_ORDER W
LEFT JOIN VW_WO_REVENUE R USING (WORK_ORDER_NUMBER)
LEFT JOIN VW_WO_LABOR L USING (WORK_ORDER_NUMBER)
LEFT JOIN BILL B USING (WORK_ORDER_NUMBER)
LEFT JOIN OTHER_COST O USING (WORK_ORDER_NUMBER);
