-- Synthetic MVP Snowflake schema. Adjust database/schema/warehouse names before use.
CREATE OR REPLACE TABLE DIM_WORK_ORDER (
    WORK_ORDER_NUMBER VARCHAR PRIMARY KEY,
    CUSTOMER VARCHAR,
    ACCOUNT VARCHAR,
    BUDGETED_PROGRAM VARCHAR,
    JOB_CATEGORY VARCHAR,
    BID_REGION VARCHAR,
    INTAKE_DATE DATE,
    PLANNED_CLOSE_DATE DATE,
    ACTUAL_CLOSE_DATE DATE,
    STATUS VARCHAR,
    TARGET_MARGIN_PCT NUMBER(8,4),
    MEDIUM_RISK_THRESHOLD_PCT NUMBER(8,4),
    HIGH_RISK_THRESHOLD_PCT NUMBER(8,4)
);

CREATE OR REPLACE TABLE FACT_WORK_UNIT_REVENUE (
    WORK_ORDER_NUMBER VARCHAR,
    SALES_ORDER_NUMBER VARCHAR,
    SALES_ORDER_LINE VARCHAR,
    WORK_UNIT_NAME VARCHAR,
    WORK_UNIT_DESCRIPTION VARCHAR,
    UNIT_TYPE VARCHAR,
    WORK_UNIT_QTY NUMBER(18,2),
    ITEM_RATE NUMBER(18,4),
    TOTAL_RATE NUMBER(18,2)
);

CREATE OR REPLACE TABLE FACT_DWR_LABOR (
    WORK_ORDER_NUMBER VARCHAR,
    DWR_NAME VARCHAR,
    TECHNICIAN VARCHAR,
    TECH_SUBSIDIARY VARCHAR,
    JOB_STOP_DATE DATE,
    MILESTONE VARCHAR,
    DUMMY_UNIT VARCHAR,
    ON_SITE_HOURS NUMBER(10,2),
    SCOPE_OF_WORK_PERFORMED VARCHAR
);

CREATE OR REPLACE TABLE FACT_BILLING (
    INVOICE_ID VARCHAR,
    WORK_ORDER_NUMBER VARCHAR,
    INVOICE_DATE DATE,
    BILLING_STATUS VARCHAR,
    BILLED_AMOUNT NUMBER(18,2)
);

CREATE OR REPLACE TABLE FACT_OTHER_COST (
    COST_ID VARCHAR,
    WORK_ORDER_NUMBER VARCHAR,
    COST_DATE DATE,
    COST_TYPE VARCHAR,
    AMOUNT NUMBER(18,2),
    DESCRIPTION VARCHAR
);

CREATE OR REPLACE TABLE DIM_LABOR_RATE (
    TECH_SUBSIDIARY VARCHAR,
    EFFECTIVE_DATE DATE,
    HOURLY_RATE NUMBER(18,2),
    CURRENCY VARCHAR,
    RATE_TYPE VARCHAR
);
